spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: hrm
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false
  flyway:
    out-of-order: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Initial
    locations: classpath:db/migration
