version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: hrm
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - back-tier
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - back-tier
networks:
  back-tier:
